### ISSUE TITLE
move to google-api-python-client

### ISSUE THREAD

**Issue by stachern** [stachern/bseu_schedule#1]
https://code.google.com/p/google-api-python-client/

change event handling accordingly.

**Comment by dskecse** [comment]
`google-api-python-client` has moved to https://github.com/googleapis/google-api-python-client.
`oauth2client` has moved to https://github.com/googleapis/oauth2client.

**Comment by dskecse** [comment]
`oauth2client` has been [deprecated](https://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html). The long-term replacement is [`google-auth`](https://google-auth.readthedocs.io/) and [`oauthlib`](http://oauthlib.readthedocs.io/).

**Comment by dskecse** [comment]
Google Calendar API v2 Deprecation notice http://web.archive.org/web/20140724091630/https://developers.google.com/google-apps/calendar/v2/developers_guide_protocol

Google Calendar API v3 (uses JSON data objects instead of the GData format) http://web.archive.org/web/20140722152825/https://developers.google.com/google-apps/calendar/

Google Calendar API v3 Migration Guide
http://web.archive.org/web/20140724082215/https://developers.google.com/google-apps/calendar/migration

https://developers.google.com/calendar/overview

**Comment by dskecse** [comment]
NOTE: Before these changes can go live, we need to [submit](https://developers.google.com/identity/protocols/oauth2/production-readiness/brand-verification) our [new Google OAuth2 consent screen](https://console.cloud.google.com/apis/credentials/consent?project=bseu-api) for verification!
